name: Release
on:
  push:
    tags: [ '*' ]
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.vars.outputs.branch }}
      tag: ${{ steps.vars.outputs.tag }}
      sha_short: ${{ steps.vars.outputs.sha_short }}
    steps:
      - uses: actions/checkout@v3
      - name: Declare variables
        id: vars
        shell: bash
        run: |
          echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
          echo "tag=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
          echo "sha_short=git rev-parse --short HEAD" >> $GITHUB_OUTPUT
  build-and-push:
    needs:
      - prepare
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Convert GitHub username to lowercase
        id: lowercase
        run: echo "REPOSITORY_LOWER=$(echo ${{ github.repository}} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ env.REPOSITORY_LOWER }}:${{ needs.prepare.outputs.tag }}


